### ISSUE TITLE
Fix Fatal error: Uncaught TypeError: Argument 1 passed to EventEspresso\core\services\request\CurrentPage::__construct() must be an instance of EE_CPT_Strategy, null given

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3608]
Howdy Brent, I don't know much about this one yet but adding the stack trace in case something sticks out for you:

```
Fatal error: Uncaught TypeError: 
Argument 1 passed to EventEspresso\core\services\request\CurrentPage::__construct() must be an instance of EE_CPT_Strategy, 
null given in /core/services/request/CurrentPage.php:68
Stack trace:
#0 [internal function]: EventEspresso\core\services\request\CurrentPage->__construct(NULL, Object(EventEspresso\core\services\request\Request))
#1 /core/EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array)
#2 /core/EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false)
#3 /core/services/loaders/CoreLoader.php(116): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, '')
#4 /core/services/loaders/CachingL in /core/services/request/CurrentPage.php on line 68
```

A user gets this error as soon as they update past 4.10.13 to current.

Any idea what it could be?

**Comment by tn3rb** [comment]
my guess is they have some custom code or a gist or something running on their site.
Can you try to get access and then look through their plugins and function.php file for any custom code plz?

I've looked over ALL of the usages of that class and everything looks good.

**Comment by Pebblo** [comment]
I tried copying all plugins and the theme locally, no issues with those.

I did some digging into this and hacked up core to get a full stack trace (they have 4.10.13.p and v4.10.17.p installed so I'm hacking up 4.10.17 and then switching back to keep them up and running).

I changed up CurrentPage.php so the constructor become this:

```
  public function __construct($cpt_strategy, RequestInterface $request)
  {
      if(! $cpt_strategy instanceof EE_CPT_Strategy ){
          $e = new \Exception;
          echo $e->getTraceAsString();
          exit('$cpt_strategy is not an instance of EE_CPT_Strategy');
      }
      $this->cpt_strategy = $cpt_strategy;
      $this->request      = $request;
      $this->initialized  = is_admin();
      // analyse the incoming WP request
      add_action('parse_request', [$this, 'parseQueryVars'], 2, 1);
  }
```

From that, when I activate EE on their site I get this:

```
#0 [internal function]: EventEspresso\core\services\request\CurrentPage->__construct(NULL, Object(EventEspresso\core\services\request\Request)) 
#1 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#2 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false) 
#3 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/CoreLoader.php(116): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, '') 
#4 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true) 
#5 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true) 
#6 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(1439): EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array, true) 
#7 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(1381): EE_Registry->_resolve_dependency('EE_Request_Hand...', 'EventEspresso\\c...', Array, 0) 
#8 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(1243): EE_Registry->_resolve_dependencies(Object(ReflectionClass), 'EE_Request_Hand...', Array) 
#9 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(913): EE_Registry->_create_object('EE_Request_Hand...', Array, 'core', false) 
#10 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(400): EE_Registry->_load(Array, 'EE_', 'EE_Request_Hand...', 'core', Array, false, true, false) 
#11 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(782): EE_Registry->load_core('EE_Request_Hand...', Array) 
#12 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/CoreLoader.php(116): EE_Registry->create('EE_Request_Hand...', Array, true, false, false, '') 
#13 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EE_Request_Hand...', Array, true) 
#14 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EE_Request_Hand...', Array, true) 
#15 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/Loader.php(105): EventEspresso\core\services\loaders\Loader->load('EE_Request_Hand...', Array) 
#16 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_System.core.php(309): EventEspresso\core\services\loaders\Loader->getShared('EE_Request_Hand...') 
#17 /wp-includes/class-wp-hook.php(303): EE_System->loadPluginApi('') 
#18 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#19 /wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#20 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Bootstrap.core.php(25): do_action('AHEE__EE_Bootst...') 
#21 /wp-includes/class-wp-hook.php(303): EE_Bootstrap::load_espresso_addons('') 
#22 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#23 /wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#24 /wp-settings.php(441): do_action('plugins_loaded') 
#25 /wp-config.php(87): require_once('/home/zimei/pub...') 
#26 /wp-load.php(50): require_once('/home/zimei/pub...') 
#27 /wp-admin/admin.php(34): require_once('/home/zimei/pub...') 
#28 /wp-admin/plugins.php(10): require_once('/home/zimei/pub...') 
#29 {main}$cpt_strategy is not an instance of EE_CPT_Strategy
#0 [internal function]: EventEspresso\core\services\request\CurrentPage->__construct(NULL, Object(EventEspresso\core\services\request\Request)) 
#1 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#2 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false) 
#3 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/CoreLoader.php(116): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, '') 
#4 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true) 
#5 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true) 
#6 /wp-content/plugins/event-espresso-core-reg_disable_new/core/services/loaders/Loader.php(105): EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array) 
#7 /wp-content/plugins/event-espresso-core-reg_disable_new/core/EE_Maintenance_Mode.core.php(265): EventEspresso\core\services\loaders\Loader->getShared('EventEspresso\\c...') 
#8 /wp-includes/class-wp-hook.php(303): EE_Maintenance_Mode->display_maintenance_mode_notice('') 
#9 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#10 /wp-includes/plugin.php(470): WP_Hook->do_action(Array) 
#11 /wp-includes/load.php(1097): do_action('shutdown') 
#12 [internal function]: shutdown_action_hook() 
#13 {main}$cpt_strategy is not an instance of EE_CPT_Strategy
```

That help at all?

**Comment by Pebblo** [comment]
Sooooo..... after I posted the above I thought about matching my server setup to their a little more.... and found the problem.

The above error is thrown with PHP7.0.33 and below.

Currently, the release version of EE4 has a min PHP version of 5.6.2.

We haven't had any other pushback on this other than with 1 user but we should probably either fix this or up the min PHP version right?

**Comment by tn3rb** [comment]
I wonder if this is somehow related to the changes in https://github.com/eventespresso/event-espresso-core/pull/3613 or whether that PR will also fix this issue. I mean, you can see that the above stack trace involves both the `CurrentPage` and ` EE_Request_Handler` classes.

**Comment by Pebblo** [comment]
Nope, unfortunately not, same error with the latest version of master.

**Comment by Pebblo** [comment]
Tested the above and unfortunately, it threw the same fatal.

So... I got curious and started playing around, turns out the fatal, and stack trace are a red herring.

The issue seems to be from list() being removed here: https://github.com/eventespresso/event-espresso-core/pull/3603/commits/1eadb922ce861e13f4c0847fe10d30295aa963af

First I removed the type declaration for EE_CPT_STrategy in CurrentPage ([HERE](https://github.com/eventespresso/event-espresso-core/blob/master/core/services/request/CurrentPage.php#L68))

Which then threw another fatal, with this:

```
[26-Nov-2021 09:32:08 UTC] PHP Parse error:  syntax error, unexpected '=' in \event-espresso-core-reg\core\admin\EE_Admin_Page.core.php on line 1033
```

That line of code is ` [$class, $method] = $func;`

That apparently works fine in PHP7.1 but does not work in PHP7.

Switch that back to using list() and re-added the type declaration again, boom, no more fatal.

**Comment by Pebblo** [comment]
Oh, wow.... so... apparently looks like the above fatal is thrown whenever there's a fatal thrown elsewhere?

Both of the above issues are PHP7 related issues, but both show the same CurrentPage.php error, which is going to be a pain for support if that's the case, any way around it?

**Comment by tn3rb** [comment]
so... it sounds like this can be closed then since it is fixed in #3620 no?

**Comment by Pebblo** [comment]
Well, sure, this is technically fixed and can likely be closed.

However, does this means that any fatal within EE moving forward are likely to just show up as the above? 

Knowing that it's not specifically `CurrentPage` causing this is there anything we can do to prevent that?

**Comment by Pebblo** [comment]
Sorry, it turns out that #3620 didn't actually fix this as I'm still getting it, guessing I missed a change I made earlier.

Currently, on PHP5.6.40 I get the same error and if I hack up CurrentPage in the same way again, I no longer get a fatal related to PHP7 changes but another fatal from CurrentPage due to the fact that cpt_strategy is null.

This:

```
[01-Dec-2021 12:47:20 UTC] PHP Fatal error:  Call to a member function get_CPT_taxonomies() on null in C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\request\CurrentPage.php on line 308
```

Here is the full stack trace from within the construct for CurrentPage when the above is thrown:

```

#0 [internal function]: EventEspresso\core\services\request\CurrentPage->__construct(NULL, Object(EventEspresso\core\services\request\Request)) 
#1 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#2 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false) 
#3 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, false) 
#4 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true) 
#5 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true) 
#6 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1440): EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array, true) 
#7 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1382): EE_Registry->_resolve_dependency('EventEspresso\\c...', 'EventEspresso\\c...', Array, 1) 
#8 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1243): EE_Registry->_resolve_dependencies(Object(ReflectionClass), 'EventEspresso\\c...', Array) 
#9 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false) 
#10 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, false) 
#11 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true) 
#12 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true) 
#13 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1440): EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array, true) 
#14 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1382): EE_Registry->_resolve_dependency('EventEspresso\\c...', 'EventEspresso\\c...', Array, 0) 
#15 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1243): EE_Registry->_resolve_dependencies(Object(ReflectionClass), 'EventEspresso\\c...', Array) 
#16 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false) 
#17 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, false) 
#18 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true) 
#19 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true) 
#20 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(105): EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array) 
#21 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_System.core.php(974): EventEspresso\core\services\loaders\Loader->getShared('EventEspresso\\c...') 
#22 [internal function]: EE_System->register_shortcodes_modules_and_widgets('') 
#23 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): call_user_func_array(Array, Array) 
#24 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#25 C:\laragon\www\ee4\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#26 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Bootstrap.core.php(61): do_action('AHEE__EE_Bootst...') 
#27 [internal function]: EE_Bootstrap::register_shortcodes_modules_and_widgets('') 
#28 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): call_user_func_array(Array, Array) 
#29 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#30 C:\laragon\www\ee4\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#31 C:\laragon\www\ee4\wp-settings.php(441): do_action('plugins_loaded') 
#32 C:\laragon\www\ee4\wp-config.php(112): require_once('C:\\laragon\\www\\...') 
#33 C:\laragon\www\ee4\wp-load.php(50): require_once('C:\\laragon\\www\\...') 
#34 C:\laragon\www\ee4\wp-blog-header.php(13): require_once('C:\\laragon\\www\\...') 
#35 C:\laragon\www\ee4\index.php(17): require('C:\\laragon\\www\\...') 
#36 {main}$cpt_strategy is not an instance of EE_CPT_Strategy


#0 [internal function]: EventEspresso\core\services\request\CurrentPage->__construct(NULL, Object(EventEspresso\core\services\request\Request)) 
#1 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#2 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\\c...', Array, '', false) 
#3 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\\c...', Array, true, false, false, false) 
#4 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\\c...', Array, true) 
#5 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\\c...', Array, true) 
#6 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(105): EventEspresso\core\services\loaders\Loader->load('EventEspresso\\c...', Array) 
#7 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Maintenance_Mode.core.php(265): EventEspresso\core\services\loaders\Loader->getShared('EventEspresso\\c...') 
#8 [internal function]: EE_Maintenance_Mode->display_maintenance_mode_notice('') 
#9 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): call_user_func_array(Array, Array) 
#10 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#11 C:\laragon\www\ee4\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#12 C:\laragon\www\ee4\wp-includes\load.php(1097): do_action('shutdown') 
#13 [internal function]: shutdown_action_hook() 
#14 {main}$cpt_strategy is not an instance of EE_CPT_Strategy
```

**Comment by Pebblo** [comment]
I did manage to bodge something that got it working in both PHP5.6.40 and PHP7 but's pretty hacky... found something interesting on the way though.

In the constructor I did this:

```
        if(! $cpt_strategy instanceof EE_CPT_Strategy ){
            $loader = LoaderFactory::getLoader();
            $cpt_strategy = $loader->getShared('EE_CPT_Strategy');
            // echo 'In here';
        }
```
(added the use for the LoaderFactory at the top of the file)

That seems to work for both PHP versions but doesn't seem right.

What I did find interesting though is with PHP7 is still get the 'In here' echo'd out to the page with the type hinting removed, if I replace it again, it doesn't.

So setting that type hinting is 'creating' an `EE_CPT_Strategy`? That doesn't make sense to me?

**Comment by Pebblo** [comment]
Yep, they don't fix this issue.

**Comment by tn3rb** [comment]
#3618 (not #3620) doesn't fix it? You pulled the `BUG/3608-REQ-loading` branch?

**Comment by Pebblo** [comment]
Yeah using `BUG/3608-REQ-loading`, iirc the above stack trace was using that branch.

I've just retested to confirm with the above branch (dropped my local branch, pulled the remote one and rebased to current master)

Using PHP5.6.4 the admin loads but any front end request shows error 500 with the usual `EE_CPT_Strategy` error, then its back to the details above:

https://github.com/eventespresso/event-espresso-core/issues/3608#issuecomment-983609718

**Comment by tn3rb** [comment]
another question, you wrote 

> if I hack up CurrentPage in the same way

can you post the changes you made plz?

re:
> What I did find interesting though is with PHP7 is still get the 'In here' echo'd out to the page with the type hinting removed, if I replace it again, it doesn't.

because with the type hinting removed, the null value is accepted, and the `if(! $cpt_strategy instanceof EE_CPT_Strategy ){` evaluates to `true` resulting in its contained logic block being executed.

re:
> So setting that type hinting is 'creating' an EE_CPT_Strategy? That doesn't make sense to me?

no, type hinting for a class will not result in one being created. Something else funky is obviously going on but without seeing all of the actual code, I'm not sure what.

**Comment by Pebblo** [comment]
> can you post the changes you made plz?

Sure but it's the change mentioned above.

I changed the constructor of CurrentPage.php to be:


```
    /**
     * CurrentPage constructor.
     *
     * @param EE_CPT_Strategy  $cpt_strategy
     * @param RequestInterface $request
     */
    public function __construct($cpt_strategy, RequestInterface $request)
    {
        if(! $cpt_strategy instanceof EE_CPT_Strategy ){
            $loader = LoaderFactory::getLoader();
            $cpt_strategy = $loader->getShared('EE_CPT_Strategy');
            // echo 'In here';
        }
        $this->cpt_strategy = $cpt_strategy;
        $this->request      = $request;
        $this->initialized  = is_admin();
        // analyse the incoming WP request
        add_action('parse_request', [$this, 'parseQueryVars'], 2, 1);
    }
```

And also added:

`use EventEspresso\core\services\loaders\LoaderFactory;` 

To the top of the class.

That's what worked in both PHP7 and PHP5.6.40

> because with the type hinting removed, the null value is accepted, and the if(! $cpt_strategy instanceof EE_CPT_Strategy ){ evaluates to true resulting in its contained logic block being executed.

Yeah but the only difference between the two requests (with regards to me and what I'm doing on the site/code) is the type hinting so shouldn't both of those requests do the same thing (be that echo out 'In here' or not).

On PHP7 with the type hinting set I would expect 'In here' to NOT be output.

Then, removing the type hinting and refreshing the same page, I would still expect it to NOT output 'In here'.

My thought behind that is that is if the `$cpt_strategy` passed the type hinting on the first request, it should be an instance of `EE_CPT_Strategy`, so then removing the type hinting should not mean it's now NOT a instance of `EE_CPT_Strategy` and trigger the output, right?

**Comment by tn3rb** [comment]
>  shouldn't both of those requests do the same thing (be that echo out 'In here' or not).

no i don't think so.

I would expect the following when passing null for the first parameter to:

- ``` __construct($cpt_strategy, RequestInterface $request) ``` should accept the null value since nothing is type hinted

- ``` __construct(EE_CPT_Strategy $cpt_strategy, RequestInterface $request) ``` should fail since null is not an instance of `EE_CPT_Strategy`

> On PHP7 with the type hinting set I would expect 'In here' to NOT be output.

yes that is correct because an error should be raised before the constructor is executed

> Then, removing the type hinting and refreshing the same page, I would still expect it to NOT output 'In here'.

nope that's incorrect. The constructor will initially accept `null` for the first parameter because you have not specified its type. That said, it _should_ raise an error because ``` __construct($cpt_strategy, RequestInterface $request) ``` does not indicate that the parameter is optional so passing `null` should be a problem. This _might_ be affected by your settings in your `php.ini` though, but I'm not enough of an expert to know what settings without digging through things for awhile.

> so then removing the type hinting should not mean it's now NOT a instance of EE_CPT_Strategy and trigger the output, right?

ug... i'm too tired atm to figure out what you mean with that tangle of double negatives... do you mean:

> removing the type hinting should now mean it's NOT an instance of EE_CPT_Strategy

if so, then yes I agree with that, or do you mean something else???

**Comment by tn3rb** [comment]
instead of 

```php
echo 'In here';
```

can you add this instead:

```php
var_dump(debug_backtrace());
```

because I want to see exactly what parameters are being passed to all of the classes throughout the stack trace, but the default PHP exception stack trace truncates everything like: `CachingLoader->load('EventEspresso\\c...', Array, true)`

**Comment by Pebblo** [comment]
Apparently Chrome didn't like the output from `var_dump(debug_backtrace());`

So I grabbed a function of SO to not truncate the stack trace (if you still want the debug_backtrace() output I'll get it next):

```
#0 (): EventEspresso\core\services\request\CurrentPage->__construct(NULL, EventEspresso\core\services\request\Request) 
#1 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#2 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\core\services\request\CurrentPage', Array, '', false) 
#3 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\core\services\request\CurrentPage', Array, true, false, false, false) 
#4 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\core\services\request\CurrentPage', Array, true) 
#5 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\core\services\request\CurrentPage', Array, true) 
#6 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1446): EventEspresso\core\services\loaders\Loader->load('EventEspresso\core\services\request\CurrentPage', Array, true) 
#7 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1382): EE_Registry->_resolve_dependency('EventEspresso\core\services\shortcodes\LegacyShortcodesManager', 'EventEspresso\core\services\request\CurrentPage', Array, 1) 
#8 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1243): EE_Registry->_resolve_dependencies(ReflectionClass, 'EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array) 
#9 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array, '', false) 
#10 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array, true, false, false, false) 
#11 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array, true) 
#12 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array, true) 
#13 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1446): EventEspresso\core\services\loaders\Loader->load('EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array, true) 
#14 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1382): EE_Registry->_resolve_dependency('EventEspresso\core\services\shortcodes\ShortcodesManager', 'EventEspresso\core\services\shortcodes\LegacyShortcodesManager', Array, 0) 
#15 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1243): EE_Registry->_resolve_dependencies(ReflectionClass, 'EventEspresso\core\services\shortcodes\ShortcodesManager', Array) 
#16 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\core\services\shortcodes\ShortcodesManager', Array, '', false) 
#17 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\core\services\shortcodes\ShortcodesManager', Array, true, false, false, false) 
#18 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\core\services\shortcodes\ShortcodesManager', Array, true) 
#19 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\core\services\shortcodes\ShortcodesManager', Array, true) 
#20 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(105): EventEspresso\core\services\loaders\Loader->load('EventEspresso\core\services\shortcodes\ShortcodesManager', Array) 
#21 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_System.core.php(974): EventEspresso\core\services\loaders\Loader->getShared('EventEspresso\core\services\shortcodes\ShortcodesManager') 
#22 (): EE_System->register_shortcodes_modules_and_widgets('') 
#23 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): call_user_func_array(Array, Array) 
#24 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#25 C:\laragon\www\ee4\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#26 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Bootstrap.core.php(61): do_action('AHEE__EE_Bootstrap__register_shortcodes_modules_and_widgets') 
#27 (): EE_Bootstrap::register_shortcodes_modules_and_widgets('') 
#28 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): call_user_func_array(Array, Array) 
#29 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#30 C:\laragon\www\ee4\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#31 C:\laragon\www\ee4\wp-settings.php(441): do_action('plugins_loaded') 
#32 C:\laragon\www\ee4\wp-config.php(112): require_once('C:\laragon\www\ee4\wp-settings.php') 
#33 C:\laragon\www\ee4\wp-load.php(50): require_once('C:\laragon\www\ee4\wp-config.php') 
#34 C:\laragon\www\ee4\wp-blog-header.php(13): require_once('C:\laragon\www\ee4\wp-load.php') 
#35 C:\laragon\www\ee4\index.php(17): require('C:\laragon\www\ee4\wp-blog-header.php') $cpt_strategy is not an instance of EE_CPT_Strategy
#0 (): EventEspresso\core\services\request\CurrentPage->__construct(NULL, EventEspresso\core\services\request\Request) 
#1 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array) 
#2 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Registry.core.php(784): EE_Registry->_create_object('EventEspresso\core\services\request\CurrentPage', Array, '', false) 
#3 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CoreLoader.php(117): EE_Registry->create('EventEspresso\core\services\request\CurrentPage', Array, true, false, false, false) 
#4 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\CachingLoader.php(158): EventEspresso\core\services\loaders\CoreLoader->load('EventEspresso\core\services\request\CurrentPage', Array, true) 
#5 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(82): EventEspresso\core\services\loaders\CachingLoader->load('EventEspresso\core\services\request\CurrentPage', Array, true) 
#6 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\services\loaders\Loader.php(105): EventEspresso\core\services\loaders\Loader->load('EventEspresso\core\services\request\CurrentPage', Array) 
#7 C:\laragon\www\ee4\wp-content\plugins\event-espresso-core-reg\core\EE_Maintenance_Mode.core.php(265): EventEspresso\core\services\loaders\Loader->getShared('EventEspresso\core\services\request\CurrentPage') 
#8 (): EE_Maintenance_Mode->display_maintenance_mode_notice('') 
#9 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(303): call_user_func_array(Array, Array) 
#10 C:\laragon\www\ee4\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#11 C:\laragon\www\ee4\wp-includes\plugin.php(470): WP_Hook->do_action(Array) 
#12 C:\laragon\www\ee4\wp-includes\load.php(1097): do_action('shutdown') 
#13 (): shutdown_action_hook() $cpt_strategy is not an instance of EE_CPT_Strategy
```

**Comment by Pebblo** [comment]
> Me: On PHP7 with the type hinting set I would expect 'In here' to NOT be output. 
>
> Brent: yes that is correct because an error should be raised before the constructor is executed

Cool, so with type hinting, I'm explicitly stating `$cpt_strategy` must be an instance of `EE_CPT_Strategy`... meaning if it wasn't an instance of `EE_CPT_Strategy` it should throw an error, right?

> Me: Then, removing the type hinting and refreshing the same page, I would still expect it to NOT output 'In here'.
> 
> Brent: nope that's incorrect. The constructor will initially accept null for the first parameter because you have not specified its type.

So as above, with type hinting enabled whatever was passed as `$cpt_strategy` had to be an instance of `EE_CPT_Strategy`.

All I've done now is remove the **requirement** for it to be an instance of `EE_CPT_Strategy` here, but as above, it had to have been one for the first request to function.

So then, on request 2 (which is just me refreshing the page after removing the type hinting) how is `$cpt_strategy` NOT an instance of `EE_CPT_Strategy`.

It must have been one on request 1... or we'd have gotten an error and just refreshing the page shouldn't change that.

But by just removing the type hinting, `$cpt_strategy` is apparently no longer an instance of `EE_CPT_Strategy`.

That's what I'm getting at.

Does that make more sense? If not don't worry about it for now :) I'm just causing more confusion with my random questions.

**Comment by tn3rb** [comment]
ok thanks for the better stack trace

I think #3623 may actually fix the issue you are seeing because you can see from the new stack trace that the `EE_CPT_Strategy` class is getting dropped by the Registry:

```php
#0 (): EE\core\services\request\CurrentPage->__construct(NULL, EE\core\services\request\Request)
#1 \core\EE_Registry.core.php(1275): ReflectionClass->newInstanceArgs(Array)
#2 \core\EE_Registry.core.php(784): EE_Registry->_create_object('EE\core\services\request\CurrentPage', Array, '', false)
```

which is exactly what was fixed in that PR.

Anyways... I ALSO took a look at our classes that register our CPTs and realized I could rearrange things a bit so that those classes are loaded earlier, and therefore available to other classes earlier, but still don't perform any of their registrations until the same time they are now. So this means that `EE_CPT_Strategy` can also be loaded earlier as well, which should also help resolve the issue you are seeing since it is ultimately being triggered by the `ShortcodesManager`

**Comment by tn3rb** [comment]
sry  hadn't refreshed the page before making my last post and therefore did not see YOUR last post... will address your commetns now...

> Me: On PHP7 with the type hinting set I would expect 'In here' to NOT be output.
> 
> Brent: yes that is correct because an error should be raised before the constructor is executed
> 
> Cool, so with type hinting, I'm explicitly stating $cpt_strategy must be an instance of EE_CPT_Strategy... meaning if it wasn't an instance of EE_CPT_Strategy it should throw an error, right?
> 
> Me: Then, removing the type hinting and refreshing the same page, I would still expect it to NOT output 'In here'.
> 
> Brent: nope that's incorrect. The constructor will initially accept null for the first parameter because you have not specified its type.
> 
> So as above, with type hinting enabled whatever was passed as $cpt_strategy had to be an instance of EE_CPT_Strategy.

oh I was assuming that `null` was being supplied the entire time, so we we either had a case where `null` was being passed to:

- `__construct($cpt_strategy`
   or
- `__construct(EE_CPT_Strategy $cpt_strategy`

in the first case, without type hinting, it may or may not raise an error depending on the server's PHP config (i think but am not 100% certain), whereas type hinting explicitly for `EE_CPT_Strategy` will definitely result in an error when `null` is supplied.

So what I _think_ is happening in the first case, is that `null` is being accepted as a valid parameter value in the constructor, but then it is hitting this conditional:

```php
	if(! $cpt_strategy instanceof EE_CPT_Strategy ){
```

which evaluates to `true` resulting in that code block to execute which includes echoing `'In here'`.

> All I've done now is remove the requirement for it to be an instance of EE_CPT_Strategy here, but as above, it had to have been one for the first request to function.

wait... are you saying that **WITH** the type hinting in place, the incoming `$cpt_strategy` parameter **IS** an instance of `EE_CPT_Strategy` and therefore does NOT echo `'In here'` (are you positive?), but then if you simply remove the type hinting and refresh, then it  echoes `'In here'`, indicating that `$cpt_strategy` is now `null`???

If that's what is happening, then my guess is that construction is failing silently due to your server's PHP configuration.
To confirm this, you should change the constructor to this:

```php
    public function __construct(EE_CPT_Strategy  $cpt_strategy, RequestInterface $request)
    {
		if ($cpt_strategy instanceof EE_CPT_Strategy ) {
			die( "$cpt_strategy IS an instance of EE_CPT_Strategy" );
		} else {
			die( "$cpt_strategy is NOT an instance of EE_CPT_Strategy" );
		}
```

that way things will grind to a halt regardless of what is passed. Do that with and without the type hinting. My guess is that you will either see the same result ("NOT an instance of EE_CPT_Strategy") OR with type hinting set you will not see anything meaning that construction is failing silently and you simply are not seeing any error for the failed type hint.

**Comment by tn3rb** [comment]
oh another possibility Tony is that there is a `try {} catch {}` block somewhere that is eating the type error and that's why you are not seeing anything when you type hint for that CPT class

**Comment by Pebblo** [comment]
> I think #3623 may actually fix the issue you are seeing because you can see from the new stack trace that the EE_CPT_Strategy class is getting dropped by the Registry

Odd, #3623 was merged into master earlier so it's active on that site with that stack trace so unfortunately, that didn't fix it.

> So can you plz pull the BUG/3608-REQ-loading branch and try again?

Winner winner chicken dinner! The latest changes in that branch fix it!

Is that change likely to cause issues elsewhere? As in do I need more extensive testing on this or would I likely know fairly quickly if this caused problems?

**Comment by Pebblo** [comment]
> wait... are you saying that WITH the type hinting in place, the incoming $cpt_strategy parameter IS an instance of EE_CPT_Strategy and therefore does NOT echo 'In here' (are you positive?), but then if you simply remove the type hinting and refresh, then it echoes 'In here', indicating that $cpt_strategy is now null???

Correct, that's exactly what is happening, this is from running PHP7.1.30:

https://monosnap.com/file/kr19WsN6d5xLNMzF1V7pzFvrPwfMrn

Literally the only change I'm making there is changing the construct type hinting.

**Comment by tn3rb** [comment]
LOLZ... 

omgosh... ok... my headspace was a mess yesterday... i know what's going on now 😆 

ok so i think that #3623 may have fixed the initial issue that was happening where the type hinting for `EE_CPT_Strategy` was not working and `CurrentPage` was receiving `null` despite that first parameter being type hinted. However I didn't realize that that PR had been merged into the one you were testing AND i was misunderstanding the results that you were getting. I was thinking that you were still getting `null` regardless of whether type hinting was in place or not.

ANYWAYS... here's what's going on now and why you are seeing what you are seeing:

- NOW that #3623 is merged in, our automatic dependency injection logic is working correctly and using our Loader class now resolves all type hinted parameters correctly. 

- type hinting the first parameter in the `CurrentPage` constructor as `EE_CPT_Strategy` will result in that class being automatically injected for that parameter

- removing the type hinting for `EE_CPT_Strategy` means that the automatic dependency injection logic would have no way of knowing what that parameter is supposed to be, and since nothing was manually provided in the incoming arguments array, nothing (ie: `null`) is supplied for that parameter.

Now... regarding my latest changes to this branch and this question of yours:

> Is that change likely to cause issues elsewhere? As in do I need more extensive testing on this or would I likely know fairly quickly if this caused problems?

I don't _think_ it will cause any other issues and here's why:

- originally in `EE_System`, some of our CPT related logic was not being loaded until the WP `init` hook-point was fired. This is because CPTs are not supposed to be registered until that point. However this was happening in two steps, the CPT related classes were being loaded, and THEN we were calling a method to perform the actual registration process. ex:

   ```php
        $register_custom_taxonomies = $this->loader->getShared(
            'EventEspresso\core\domain\services\custom_post_types\RegisterCustomTaxonomies'
        );
        $register_custom_taxonomies->registerCustomTaxonomies();
   ``` 

- the constructors for the CPT related classes like `RegisterCustomTaxonomies` were not performing any side effects other than setting properties for any incoming parameters, which is a good practice to follow (ie: constructors do nothing but construct the class instance). 

- the above point means that the loading and construction of those classes and the actual CPT registration process do not have to occur at the same time. The loading of those classes was moved to a point just before the `ShortcodeManager` was loaded, but the actual CPT registration process was kept where it was. So loading is now happening during the WP `plugins_loaded` hook-point and registration is still happening during the `init` hook-point where it needs to be.

- how does this fix the issue? By ensuring that dependencies are all constructed properly and available for injection into the classes that need them. Here's how things flowed:

	- the `ShortcodesManager` depended on `CurrentPage` in order to determine if the current request was for an espresso page and whether we needed to load all of our shortcodes and parse the post content for them. 
	- in order for  `CurrentPage` to be able to determine if the current request was for an EE CPT, it depended on some basic details about our CPTs
	- our CPTs were not loaded until later as described above

So now that the loading  order is rearranged things are working correctly. It's weird though because before this error started happening, we were loading the `EE_Request_Handler` earlier and it essentially contained the same logic that has now been extracted into `CurrentPage`. So that class depended on our CPTs as well, and yet, for some reason, it didn't choke, but `CurrentPage` does?!?!?

**Comment by Pebblo** [comment]
Ayyyee good stuff! I follow most of that so thank you for the explanation :)
